### ISSUE TITLE
Create a dice

### ISSUE THREAD

**Issue by OuuGiii** [OuuGiii/CG-PROJECT-4#3]
- The dice should be a single solid to which a texture and bump map are also applied to simulate the relief of the numbers (or other figures) present on each face of the dice.
- The die must lie on one of its vertices on the center of the board and rotate on itself. [1.0 value]

**Comment by OuuGiii** [comment]
I saw that you have created a new folder "img" inside of the folder "js". By moving the images to the other "img" folder (that is not inside of the "js" folder) the images becomes visible in the sources :)

**Comment by dserafim1999** [comment]
ahhhh might be that! but wasn't intentional, my bad

**Comment by OuuGiii** [comment]
According to this answer: https://stackoverflow.com/a/35883939 CubeTextureLoader should be used for CubeMap and texture loader should be used instead. 

The answer below shows a way how to do it correctly: https://stackoverflow.com/a/50645451
