### ISSUE TITLE
Make pausing possible

### ISSUE THREAD

**Issue by OuuGiii** [OuuGiii/CG-PROJECT-4#7]
- It shall be allowed to pause the display when the user presses the 'S' key and resume by pressing the key again.
- While paused, a message should be displayed on the screen that should always be readable, regardless of the camera position.

**Comment by OuuGiii** [comment]
They added a suggestion for how to pause in the description of this project, and it went like this:

> To pause, just “freeze” the time. This will require the use of a few lines of code.

**Comment by dserafim1999** [comment]
> They added a suggestion for how to pause in the description of this project, and it went like this:
> 
> > To pause, just “freeze” the time. This will require the use of a few lines of code.

yeah, I think that means not to update movement when it's paused like I did... but we have to add a texture or something with text that says it's paused or something, we need to look at that tomorrow

**Comment by OuuGiii** [comment]
This link provides four different ways of adding text: https://threejs.org/docs/#manual/en/introduction/Creating-text

**Comment by OuuGiii** [comment]
Here is an answer with links to other answer on how to do it with the texture thing: https://stackoverflow.com/a/20162906/6209399

I don't really understand why we should do it by applying a texture as it be much smarter to do it with HTML and CSS and it will always be dynamic. But if we are going to do it with textures then the above link should provide a solution for that.
